---
title: "Assignment 4 Lobsters"
author: "Andrew Salvador & Benson Truong"
date: "11/12/2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

```


```{r}
library(tidyverse)
library(janitor)
```


```{r}
lobster_data <- read_csv("lobster_abundance_sbc_lter.csv") %>% 
  clean_names() 

lobster_data_clean <- lobster_data %>% 
  tidyr::uncount(count)

lobster_bysite <- lobster_data_clean %>% 
  count(year, site)

```



```{r}
# RESULTS A
# IVEE LOBSTER COUNT

lobster_ivee <- lobster_bysite %>% 
  filter(site %in% c("IVEE"))
  
lobster_factorivee <- lobster_ivee %>% 
  mutate(year = as.character(year)) 


ggplot(lobster_factorivee, aes(x = year,
                           y = n)) +
  geom_col(width = .8) +
  labs(x = "Year",
       y = "Count",
       title = "Lobster count in Isla Vista (MPA) 2012-2018") +
  scale_y_continuous(limits = c(0, 1000), expand = c(0,0)) 
  



```

  
```{r}
#RESULTS A:
#CARP LOBSTER COUNT
lobster_carp <- lobster_bysite %>% 
  filter(site %in% c("CARP"))
  
lobster_factorcarp <- lobster_carp %>% 
  mutate(year = as.character(year)) 


ggplot(lobster_factorcarp, aes(x = year,
                           y = n)) +
  geom_col(width = .8) +
  labs(x = "Year",
       y = "Count",
       title = "Lobster count in Carpinteria (Non-MPA) 2012-2018") +
  scale_y_continuous(limits = c(0, 750), expand = c(0,0)) 

```


```{r}

#RESULTS A
#MOHAWK Lobster count 2012-2018

lobster_mohk <- lobster_bysite %>% 
  filter(site %in% c("MOHK"))
  
lobster_factormohk <- lobster_mohk %>% 
  mutate(year = as.character(year)) 


ggplot(lobster_factormohk, aes(x = year,
                           y = n)) +
  geom_col(width = .8) +
  labs(x = "Year",
       y = "Count",
       title = "Lobster count in Mohawk (Non-MPA) 2012-2018") +
  scale_y_continuous(limits = c(0, 350), expand = c(0,0)) 
```

```{r}
# RESULTS A
#NAPLES (NAPL) Lobster count

lobster_napl <- lobster_bysite %>% 
  filter(site %in% c("MOHK"))
  
lobster_factornapl <- lobster_napl %>% 
  mutate(year = as.character(year)) 


ggplot(lobster_factornapl, aes(x = year,
                           y = n)) +
  geom_col(width = .8) +
  labs(x = "Year",
       y = "Count",
       title = "Lobster count in Naples (MPA) 2012-2018") +
  scale_y_continuous(limits = c(0, 350), expand = c(0,0)) 
```


```{r}
# RESULTS A
# ARROYO QUEMADO (AQUE) Lobster count

lobster_aque <- lobster_bysite %>% 
  filter(site %in% c("AQUE"))
  
lobster_factoraque <- lobster_aque %>% 
  mutate(year = as.character(year)) 


ggplot(lobster_factoraque, aes(x = year,
                           y = n)) +
  geom_col(width = .8) +
  labs(x = "Year",
       y = "Count",
       title = "Lobster count in Arroyo Quemado (Non-MPA) 2012-2018") +
  scale_y_continuous(limits = c(0, 125), expand = c(0,0)) 
```
























































































































































```{r}
# RESULTS B
# For 2012
lobster_data_2012 <- lobster_data_clean %>% 
  filter(year == "2012")

ggplot(data = lobster_data_2012, aes(x = size_mm))+
  geom_histogram(aes(fill = site))+
  facet_wrap(~site, scales ="free")+
  labs(x = "Size (mm)", y = "Counts", title = "2012 Lobster Size Distribution")

# For 2018
lobster_data_2018 <- lobster_data_clean %>% 
  filter(year == "2018")

ggplot(data = lobster_data_2018, aes(x = size_mm))+
  geom_histogram(aes(fill = site))+
  facet_wrap(~site, scales = "free")+
  labs(x = "Size (mm)", y = "Counts", title = "2018 Lobster Size Distribution")
                
```

```{r}
# RESULTS C

# For 2012--------------------------------
lobster_smry_2012 <- lobster_data_2012 %>% 
  group_by(site) %>% 
  summarise(mean_size = mean(size_mm, na.rm = TRUE),
            sd_size= sd(size_mm, na.rm = TRUE),
            sample_n = n())

# Mean size(mm) for Marine Protected Areas (MPA)
lobster_smry_mpa_2012 <- lobster_data_2012 %>% 
  filter(site %in% c("IVEE", "NAPL")) 
mean_mpa_2012 <- mean(lobster_smry_mpa_2012$size_mm, na.rm = TRUE)


# Mean size(mm) for Non-Marine Protected Areas (Non-MPA)
lobster_smry_non_mpa_2012 <- lobster_data_2018 %>% 
  filter(site %in% c("AQUE", "MOHK", "CARP"))
mean_non_mpa_2012 <- mean(lobster_smry_non_mpa_2012$size_mm, na.rm = TRUE)
            
  

##For 2018---------------------------------
lobster_smry_2018 <- lobster_data_2018 %>% 
  group_by(site) %>% 
  summarise(mean_size = mean(size_mm, na.rm = TRUE),
            sd_size= sd(size_mm, na.rm = TRUE),
            sample_n = n())

# Mean size(mm) for Marine Protected Areas (MPA)
lobster_smry_mpa_2018 <- lobster_data_2018 %>% 
  filter(site %in% c("IVEE", "NAPL"))
mean_mpa_2018 <- mean(lobster_smry_mpa_2018$size_mm, na.rm = TRUE)

# Mean size(mm) for Non-Marine Protected Areas (Non-MPA)
lobster_smry_non_mpa_2018 <- lobster_data_2018 %>% 
  filter(site %in% c("AQUE", "MOHK", "CARP"))
mean_non_mpa_2018 <- mean(lobster_smry_mpa_2018$size_mm, na.rm = TRUE)


  

  
```

```{r}
# MPA Lobsters 2012
#One sample t-test..
mpa_lobsters_2012 <- lobster_smry_mpa_2012 %>% 
  filter(site %in% c("IVEE", "NAPL")) %>% 
  pull(size_mm)

t.test(mpa_lobsters_2012)
```

```{r}
#MPA Lobsters 2018
mpa_lobsters_2018 <- lobster_smry_mpa_2018 %>% 
  filter(site %in% c("IVEE", "NAPL")) %>% 
  pull(size_mm)

t.test(mpa_lobsters_2018)
```

```{r}
# Results C, Question 3. 
#2 Sample t-test MPA lobsters 2012 and 2018
mpa_2012_2018_ttest <- t.test(mpa_lobsters_2012, mpa_lobsters_2018)
mpa_2012_2018_ttest
```

Mean lobster size in MPA sites differed significantly from 2012 to 2018 (t(`r round(mpa_2012_2018_ttest$parameter, 2)`) = `r round(mpa_2012_2018_ttest$statistic, 2)`, *p* < .001).
